"""
SQLAlchemy database models for users, documents, and summaries.

Stage 5: Persistent storage for document metadata and generated legal summaries.
Stage 6: User accounts and document ownership (documents.user_id → users.id).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import List, Optional

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.session import Base


def _generate_uuid() -> str:
    return str(uuid.uuid4())


class User(Base):
    """Registered application user. password_hash is never exposed via API schemas."""

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=_generate_uuid,
        index=True,
        doc="Unique user identifier (UUID)",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
        index=True,
        doc="Unique login email (stored lowercase)",
    )
    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="bcrypt password hash — never returned in API responses",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp of account creation",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Timestamp of last update",
    )

    documents: Mapped[List["Document"]] = relationship(
        "Document",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )


class Document(Base):
    """
    Persisted metadata and status for uploaded legal and tax documents.

    Note: The actual binary contents (PDF, text) are handled via secure temporary
    storage and not stored inside the relational database.
    """

    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=_generate_uuid,
        index=True,
        doc="Unique document identifier (UUID)",
    )
    filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Sanitized display filename",
    )
    file_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        doc="MIME type of the document (e.g. application/pdf, text/plain)",
    )
    file_size: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Document size in bytes",
    )
    processing_status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="completed",
        doc="Processing lifecycle state: uploaded, processing, completed, failed",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp of initial document record creation",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Timestamp of last update",
    )
    user_id: Mapped[Optional[str]] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        doc=(
            "Owning user (users.id). Nullable only to preserve Stage 5 rows that "
            "predate authentication; new uploads always set this from the JWT user."
        ),
    )

    user: Mapped[Optional["User"]] = relationship(
        "User",
        back_populates="documents",
    )

    # 1-to-many relationship with Summary with full cascade delete
    summaries: Mapped[List["Summary"]] = relationship(
        "Summary",
        back_populates="document",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="desc(Summary.created_at)",
    )

    @property
    def document_id(self) -> str:
        """Alias property matching Stage 2/3/4 naming convention."""
        return self.id

    @property
    def file_size_bytes(self) -> int:
        """Alias property matching schema naming convention."""
        return self.file_size

    @property
    def mime_type(self) -> str:
        """Alias property matching schema naming convention."""
        return self.file_type


class Summary(Base):
    """
    Persisted summary generated by the NLP pipeline for an analyzed document.
    """

    __tablename__ = "summaries"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=_generate_uuid,
        index=True,
        doc="Unique summary identifier (UUID)",
    )
    document_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key reference to documents.id",
    )
    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Legal document summary text generated by the NLP pipeline",
    )
    processing_time: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        doc="Summary processing latency in seconds",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp of summary generation",
    )

    # Relationship back to Document
    document: Mapped["Document"] = relationship(
        "Document",
        back_populates="summaries",
    )
