"""
Pydantic schemas for document operations and persistence.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field
from backend.app.schemas.error import ErrorDetail, ErrorResponse


class DocumentUploadResponse(BaseModel):
    """Successful response body for POST /api/v1/documents/upload."""

    success: bool = Field(
        True,
        description="Indicates whether document upload and parsing was successful",
    )
    document_id: str = Field(
        ...,
        description="Unique processing identifier generated for this document",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )
    filename: str = Field(
        ...,
        description="Sanitized display filename (never an internal filesystem path)",
        examples=["form16.pdf"],
    )
    file_size_bytes: int = Field(
        ...,
        ge=0,
        description="Size of the uploaded document in bytes",
        examples=[634075],
    )
    mime_type: str = Field(
        ...,
        description="MIME type detected for the uploaded document",
        examples=["application/pdf"],
    )
    char_count: int = Field(
        ...,
        ge=0,
        description="Number of text characters extracted from the document",
        examples=[12340],
    )
    preview: str = Field(
        ...,
        description="Initial text preview extracted from the document (up to 500 characters)",
        examples=["FORM 16 — Certificate under section 203 of the Income-tax Act..."],
    )
    message: str = Field(
        "Document uploaded and text extracted successfully",
        description="Human-readable status message",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "filename": "form16.pdf",
                "file_size_bytes": 634075,
                "mime_type": "application/pdf",
                "char_count": 12340,
                "preview": "FORM 16 — Certificate under section 203 of the Income-tax Act...",
                "message": "Document uploaded and text extracted successfully",
            }
        }
    }


class SummaryItemResponse(BaseModel):
    """Summary item schema for document history and details."""

    id: str = Field(..., description="Unique summary identifier (UUID)")
    document_id: str = Field(..., description="Referenced document identifier (UUID)")
    summary: str = Field(..., description="Legal and tax summary generated by the NLP pipeline")
    processing_time: Optional[float] = Field(None, description="Processing execution time in seconds")
    created_at: datetime = Field(..., description="Timestamp when the summary was generated")

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": "770e8400-e29b-41d4-a716-446655440001",
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "summary": "Form 16 Summary: Total gross salary INR 12,00,000...",
                "processing_time": 1.25,
                "created_at": "2026-09-19T10:00:00Z",
            }
        },
    }


class DocumentResponse(BaseModel):
    """Document metadata schema for listing and retrieval.

    Public identifier is ``document_id`` (mapped from ``documents.id``).
    The database primary key is not exposed as a separate ``id`` field.
    """

    document_id: str = Field(..., description="Canonical public document identifier (UUID)")
    filename: str = Field(..., description="Sanitized display filename")
    file_type: str = Field(..., description="MIME type or file format")
    file_size: int = Field(..., ge=0, description="Size in bytes")
    processing_status: str = Field(..., description="Current processing lifecycle status")
    created_at: datetime = Field(..., description="Record creation timestamp")
    updated_at: datetime = Field(..., description="Last record update timestamp")

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "filename": "tax.txt",
                "file_type": "text/plain",
                "file_size": 998,
                "processing_status": "completed",
                "created_at": "2026-09-19T10:00:00Z",
                "updated_at": "2026-09-19T10:00:00Z",
            }
        },
    }


class DocumentDetailResponse(BaseModel):
    """Detailed document record schema including associated summaries."""

    document_id: str = Field(..., description="Canonical public document identifier (UUID)")
    filename: str = Field(..., description="Sanitized display filename")
    file_type: str = Field(..., description="MIME type or file format")
    file_size: int = Field(..., ge=0, description="Size in bytes")
    processing_status: str = Field(..., description="Current processing lifecycle status")
    created_at: datetime = Field(..., description="Record creation timestamp")
    updated_at: datetime = Field(..., description="Last record update timestamp")
    summaries: List[SummaryItemResponse] = Field(
        default_factory=list,
        description="Persisted summaries for this document (empty list if none exist)",
    )

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "filename": "tax.txt",
                "file_type": "text/plain",
                "file_size": 998,
                "processing_status": "completed",
                "created_at": "2026-09-19T10:00:00Z",
                "updated_at": "2026-09-19T10:00:00Z",
                "summaries": [
                    {
                        "id": "770e8400-e29b-41d4-a716-446655440001",
                        "document_id": "550e8400-e29b-41d4-a716-446655440000",
                        "summary": "Form 16 Summary: Total gross salary INR 12,00,000...",
                        "processing_time": 1.25,
                        "created_at": "2026-09-19T10:00:00Z",
                    }
                ],
            }
        },
    }


class DocumentListResponse(BaseModel):
    """Paginated or complete list of persisted document records."""

    success: bool = Field(True, description="Indicates request success")
    total: int = Field(..., ge=0, description="Total number of documents matching query")
    documents: List[DocumentResponse] = Field(default_factory=list, description="List of document metadata items")

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "total": 1,
                "documents": [
                    {
                        "document_id": "550e8400-e29b-41d4-a716-446655440000",
                        "filename": "tax.txt",
                        "file_type": "text/plain",
                        "file_size": 998,
                        "processing_status": "completed",
                        "created_at": "2026-09-19T10:00:00Z",
                        "updated_at": "2026-09-19T10:00:00Z",
                    }
                ],
            }
        }
    }


class DocumentDeleteResponse(BaseModel):
    """Response returned upon successful document deletion."""

    success: bool = Field(True, description="Indicates whether deletion was successful")
    document_id: str = Field(..., description="Identifier of the deleted document")
    message: str = Field(
        "Document and associated summaries deleted successfully",
        description="Human-readable status message",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "message": "Document and associated summaries deleted successfully",
            }
        }
    }


__all__ = [
    "DocumentUploadResponse",
    "DocumentResponse",
    "DocumentDetailResponse",
    "DocumentListResponse",
    "DocumentDeleteResponse",
    "SummaryItemResponse",
    "ErrorDetail",
    "ErrorResponse",
]
