"""
Pydantic schemas for the document summarization endpoint.
"""

from __future__ import annotations

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class SummarizeResponse(BaseModel):
    """Successful response body for POST /api/v1/summarize."""

    success: bool = Field(True, description="Indicates if summarization was successful")
    filename: str = Field(..., description="Sanitized document filename (display only)")
    document_id: str = Field(..., description="Unique document processing identifier")
    file_size_bytes: int = Field(..., description="Size of the uploaded document in bytes")
    char_count: int = Field(..., description="Number of characters in the extracted text")
    summary: str = Field(..., description="Legal and tax summary generated by the NLP pipeline")
    processing_time: float = Field(..., description="Total processing time in seconds")
    message: str = Field(
        "Document summarized successfully",
        description="Human-readable status message",
    )
    insights: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional statutory RAG insights if available from the pipeline",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "filename": "tax.txt",
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "file_size_bytes": 450,
                "char_count": 412,
                "summary": "Form 16 summary: Gross salary Rs. 12,00,000. Deductions claimed under Section 80C: Rs. 1,50,000. Tax liability is Rs. 1,05,000. ITR due date: 31st July 2026.",
                "processing_time": 1.85,
                "message": "Document summarized successfully",
            }
        }
    }
