"""
Pydantic schemas for the document summarization endpoints.
"""

from __future__ import annotations

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, field_validator

_ALLOWED_PROVIDERS = {"openai", "ollama", "local", "extractive", "auto"}


class SummarizeRequest(BaseModel):
    """
    Request payload for text-based legal document summarization.
    """

    text: str = Field(
        ...,
        min_length=5,
        max_length=500_000,
        description="The raw legal or tax document text to summarize (minimum 5 characters).",
        examples=[
            "Form 16 Part B: Gross salary Rs. 12,00,000. Deductions claimed under Section 80C: Rs. 1,50,000. "
            "Total taxable income: Rs. 10,50,000. Tax payable: Rs. 1,05,000. TDS deposited: Rs. 1,05,000."
        ],
    )
    provider: Optional[str] = Field(
        None,
        description="Optional LLM provider override ('openai', 'ollama', 'local', 'extractive', 'auto')",
        examples=["extractive"],
    )
    document_name: Optional[str] = Field(
        None,
        max_length=255,
        description="Optional document or filename reference for tracking and display",
        examples=["tax_return_summary.txt"],
    )
    document_id: Optional[str] = Field(
        None,
        description=(
            "Optional existing document UUID. When provided, the summary is stored "
            "against that document and no new Document row is created. When omitted, "
            "a new document record is created (backward-compatible default)."
        ),
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    @field_validator("provider")
    @classmethod
    def validate_provider(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None
        cleaned = value.strip().lower()
        if cleaned not in _ALLOWED_PROVIDERS:
            allowed = ", ".join(f"'{p}'" for p in sorted(_ALLOWED_PROVIDERS))
            raise ValueError(f"Invalid provider '{value}'. Allowed providers: {allowed}")
        return cleaned

    model_config = {
        "json_schema_extra": {
            "example": {
                "text": (
                    "Form 16 Part B: Gross salary Rs. 12,00,000. Deductions claimed under Section 80C: Rs. 1,50,000. "
                    "Total taxable income: Rs. 10,50,000. Tax payable: Rs. 1,05,000. TDS deposited: Rs. 1,05,000."
                ),
                "provider": "auto",
                "document_name": "Form16_2026.txt",
            }
        }
    }


class SummarizeResponse(BaseModel):
    """Successful response body for summarization endpoints."""

    success: bool = Field(
        True,
        description="Indicates if summarization was successful",
    )
    filename: str = Field(
        ...,
        description="Sanitized document filename (display only)",
        examples=["tax.txt"],
    )
    document_id: str = Field(
        ...,
        description="Unique document processing identifier",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )
    file_size_bytes: int = Field(
        ...,
        ge=0,
        description="Size of the document in bytes",
        examples=[450],
    )
    char_count: int = Field(
        ...,
        ge=0,
        description="Number of characters in the extracted text",
        examples=[412],
    )
    summary: str = Field(
        ...,
        description="Legal and tax summary generated by the NLP pipeline",
        examples=[
            "Form 16 summary: Gross salary Rs. 12,00,000. Deductions claimed under Section 80C: Rs. 1,50,000. "
            "Tax liability is Rs. 1,05,000. ITR due date: 31st July 2026."
        ],
    )
    processing_time: float = Field(
        ...,
        ge=0.0,
        description="Total processing time in seconds",
        examples=[1.85],
    )
    message: str = Field(
        "Document summarized successfully",
        description="Human-readable status message",
    )
    provider: Optional[str] = Field(
        None,
        description="LLM provider utilized for summarization",
        examples=["openai"],
    )
    insights: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional statutory RAG insights if available from the pipeline",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "filename": "tax.txt",
                "document_id": "550e8400-e29b-41d4-a716-446655440000",
                "file_size_bytes": 450,
                "char_count": 412,
                "summary": "Form 16 summary: Gross salary Rs. 12,00,000. Deductions claimed under Section 80C: Rs. 1,50,000. Tax liability is Rs. 1,05,000. ITR due date: 31st July 2026.",
                "processing_time": 1.85,
                "message": "Document summarized successfully",
                "provider": "openai",
                "insights": None,
            }
        }
    }


__all__ = ["SummarizeRequest", "SummarizeResponse"]
